---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Post Types
- type: directory
  path: _posts/projects
  label: projects
  create: all
  match: "**/*"
  templates:
  - projects
- type: directory
  path: _posts/snippets
  label: snippets
  create: all
  match: "**/*"
  templates:
  - snippets
- type: directory
  path: _posts/posts
  label: posts
  create: all
  match: "**/*"
  templates:
  - posts
upload_dir: public
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - NEXT_PUBLIC_DOMAIN=https://dennyh.me
  - NEXT_PUBLIC_MAILCHIMP_API_KEY=0d4c5e8d313ba8975cbd8deedde289f6-us19
  - NEXT_PUBLIC_MAILCHIMP_SERVER=us19
  - NEXT_PUBLIC_MAILCHIMP_LIST_ID=000061ca08
  preview_output_directory: ".next"
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
